---
title: Casos de Uso - NexusClass
---
%%{init: {"flowchart": {"curve": "linear", "nodeSpacing": 50, "rankSpacing": 85, "useMaxWidth": false}} }%%
flowchart LR
    classDef usecase fill:#ffffff,stroke:#1f1f1f,color:#1f1f1f,stroke-width:2px;
    classDef actor color:#1f1f1f;

    Professores@{ icon: "fa:user", label: "Professores", pos: "b", h: 56 }
    Corpo@{ icon: "fa:user", label: "Membros do corpo", pos: "b", h: 56 }
    Estudantes@{ icon: "fa:user", label: "Estudantes", pos: "b", h: 56 }
    Administradores@{ icon: "fa:user", label: "Administradores", pos: "b", h: 56 }

    Professores ~~~ Corpo
    Corpo ~~~ Estudantes
    Estudantes ~~~ Administradores

    subgraph Sistema["Sistema NexusClass"]
        direction TB
        UC_Acessar(("Acessar sistema"))
        UC_Pesquisar(("Pesquisar turmas"))
        UC_Inscricao(("Inscrever-se na turma"))
        UC_Mural(("Abrir mural da turma"))
        UC_Publicar(("Publicar mensagem"))
        UC_Calendario(("Visualizar calendário"))
        UC_Suporte(("Acessar suporte"))
        UC_Config(("Alterar tema e configurações"))
    end

    class UC_Acessar,UC_Pesquisar,UC_Inscricao,UC_Mural,UC_Publicar,UC_Calendario,UC_Suporte,UC_Config usecase
    class Professores,Corpo,Estudantes,Administradores actor

    Professores --> UC_Mural
    Corpo --> UC_Calendario
    Estudantes --> UC_Pesquisar
    Administradores --> UC_Config

    UC_Mural -. extend .-> UC_Publicar
    UC_Pesquisar -. include .-> UC_Inscricao
    UC_Acessar -.-> UC_Pesquisar

    Professores ~~~ UC_Mural
    Corpo ~~~ UC_Calendario
    Estudantes ~~~ UC_Pesquisar
    Administradores ~~~ UC_Config

    linkStyle default stroke:#9ca3af,stroke-width:1.25px,fill:none,opacity:1
