import type { FormField } from "@/hooks/SuporteHooks/type";
export const formFields: FormField[] = [
  {
    key: "name",
    titulo: "Nome",
    id: "nome",
    nome: "from_name",
    escritoNoInputbox: "Digite seu nome completo",
    decricao: "Nome de quem está solicitando o suporte.",
    required: true,
  },
  {
    key: "email",
    titulo: "Email",
    id: "email",
    nome: "reply_to",
    escritoNoInputbox: "Digite seu email",
    decricao: "Usado para retorno da equipe.",
    tipo: "email",
    required: true,
  },
  {
    key: "subject",
    titulo: "Assunto",
    id: "subject",
    nome: "subject",
    escritoNoInputbox: "Selecione o assunto",
    decricao: "Selecione o assunto que melhor descreve o problema.",
    inputOption: [
      { label: "Dúvida geral sobre o site", value: "duvida-geral" },
      { label: "Erro técnico no site", value: "erro-tecnico" },
      { label: "Solicitação de recurso ou melhoria", value: "solicitacao-recurso" },
      { label: "Erro de visualização do mural", value: "erro-visualizacao-mural" },
      { label: "Erro de visualização do perfil", value: "erro-visualizacao-perfil" },
      { label: "Erro de visualização das atividades", value: "erro-visualizacao-atividades" },
      { label: "Erro de visualização dos posts", value: "erro-visualizacao-posts" },
      { label: "Erro de visualização das dúvidas", value: "erro-visualizacao-duvidas" },
      { label: "Erro de visualização das pesquisas", value: "erro-visualizacao-pesquisas" },
      { label: "Erro de visualização do calendário", value: "erro-visualizacao-calendario" },
      { label: "Erro de comunicação com o chatbot", value: "erro-comunicacao-chatbot" },
      { label: "Erro de acesso as configurações avançadas", value: "erro-acesso-configuracoes" },
      { label: "Acesso à conta", value: "acesso-conta" },
      { label: "Atendimento urgente", value: "atendimento-urgente" },
    ],
    required: true,
  },
  {
    key: "message",
    titulo: "Mensagem",
    id: "message",
    nome: "message",
    escritoNoInputbox:
      "Descreva o problema, passos para reproduzir e o que você esperava acontecer.",
    decricao: "Inclua prints, tela afetada e horário, se possível.",
    textArea: true,
    required: true,
  },
]